function [pose] = initPlaceRandom(width,length,ImageOc)
%initPlaceRandom This function returns a random point(x,y)which does not
%collide with obstacles, or is outside the map limits.
%   Input: width, length - of map
%          ImageOc - a matrix where 1's are obstacles, 0's are open space
%   Output: x,y - piint in the map
matSize = size(ImageOc);
matWidth = matSize(1);
matLength = matSize(2);
a = width/matWidth;
b = length/matLength;
x = 3 + rand*(matWidth - 6);
y = 3 + rand*(matLength - 6);

while   ImageOc(round(x),round(y)) == 1 || ImageOc(round(x),round(y + 2.5)) == 1 ...
        || ImageOc(round(x),round(y - 2.5)) == 1 || ImageOc(round(x + 2.5),round(y)) == 1 ...
        || ImageOc(round(x - 2.5),round(y)) == 1 || ImageOc(round(x + 2.5),round(y + 2.5)) == 1 ...
        || ImageOc(round(x - 2.5),round(y - 2.5)) == 1 || ImageOc(round(x),round(y + 1.5)) == 1 ...
        || ImageOc(round(x),round(y - 1.5)) == 1 || ImageOc(round(x + 1.5),round(y)) == 1 ...
        || ImageOc(round(x - 1.5),round(y)) == 1 || ImageOc(round(x + 1.5),round(y + 1.5)) == 1 ...
        || ImageOc(round(x - 1.5),round(y - 1.5)) == 1 || ImageOc(round(x),round(y + 0.5)) == 1 ...
        || ImageOc(round(x),round(y - 0.5)) == 1 || ImageOc(round(x + 0.5),round(y)) == 1 ...
        || ImageOc(round(x - 0.5),round(y)) == 1 || ImageOc(round(x + 0.5),round(y + 0.5)) == 1 ...
        || ImageOc(round(x - 0.5),round(y - 0.5)) == 1 || ImageOc(round(x),round(y + 0.25)) == 1 ...
        || ImageOc(round(x),round(y - 0.25)) == 1 || ImageOc(round(x + 0.25),round(y)) == 1 ...
        || ImageOc(round(x - 0.25),round(y)) == 1 || ImageOc(round(x + 0.25),round(y + 0.25)) == 1 ...
        || ImageOc(round(x - 0.25),round(y - 0.25)) == 1 || ImageOc(round(x),round(y + 1)) == 1 ...
        || ImageOc(round(x),round(y - 1)) == 1 || ImageOc(round(x + 1),round(y)) == 1 ...
        || ImageOc(round(x - 1),round(y)) == 1 || ImageOc(round(x + 1),round(y + 1)) == 1 ...
        || ImageOc(round(x - 1),round(y - 1)) == 1
    
    x = 3 + rand*(matLength - 6);
    y = 3 + rand*(matWidth - 6);
end

pose(1) = (y)*b;
pose(2) = (matWidth - x)*a;
end

